{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "2ue5pzh2rfgs3epxwqcs3bun5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.3.1-SNAPSHOT.jar",
          "url": "javapackager-1.3.1-SNAPSHOT.jar",
          "size": 378781,
          "sha512": "633b1699a89e9727a659f061d9b4df4d9baa2094d084ec79ab840dd0c46c32791fc7ec3443283b40782547f6c76b1d3f9b980832326ac8fc5355d5c90be96d8c",
          "sha256": "beec106472b618ef5e3cf4d1fd70d6400f3372203c5e00b24294ed88904b8820",
          "sha1": "127e205be4f0b48ae02edca53b1347dd6adff2c1",
          "md5": "95b3c979e8caa39183ed7415d7a2c4f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "gradle-launch4j",
          "version": {
            "requires": "2.4.7"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.3.1-SNAPSHOT.jar",
          "url": "javapackager-1.3.1-SNAPSHOT.jar",
          "size": 378781,
          "sha512": "633b1699a89e9727a659f061d9b4df4d9baa2094d084ec79ab840dd0c46c32791fc7ec3443283b40782547f6c76b1d3f9b980832326ac8fc5355d5c90be96d8c",
          "sha256": "beec106472b618ef5e3cf4d1fd70d6400f3372203c5e00b24294ed88904b8820",
          "sha1": "127e205be4f0b48ae02edca53b1347dd6adff2c1",
          "md5": "95b3c979e8caa39183ed7415d7a2c4f0"
        }
      ]
    }
  ]
}
