{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.6-WHY4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "o6dq3fncobhpthtnlep5mep2ua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.6-WHY4.jar",
          "url": "javapackager-1.6.6-WHY4.jar",
          "size": 1455718,
          "sha512": "ed7d08798e8e2764ac94f0fa572ee572413d848dfd37e90797a2a30e706c58f1c3ae3a45669d99d28cb0c1d565d2ea98cda77cb94f2875e7a3ea501e637c05d2",
          "sha256": "a27bcd06bf03b2e2601ca03ff22575b04bdc3d2dec4aada101e4c9d8a0d9dde7",
          "sha1": "6a5970db199b2b5728f36ceed16a504504c11977",
          "md5": "66e39ce250ec8d8581730825e34d7c5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "launch4j",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.6-WHY4.jar",
          "url": "javapackager-1.6.6-WHY4.jar",
          "size": 1455718,
          "sha512": "ed7d08798e8e2764ac94f0fa572ee572413d848dfd37e90797a2a30e706c58f1c3ae3a45669d99d28cb0c1d565d2ea98cda77cb94f2875e7a3ea501e637c05d2",
          "sha256": "a27bcd06bf03b2e2601ca03ff22575b04bdc3d2dec4aada101e4c9d8a0d9dde7",
          "sha1": "6a5970db199b2b5728f36ceed16a504504c11977",
          "md5": "66e39ce250ec8d8581730825e34d7c5d"
        }
      ]
    }
  ]
}
