{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fbh5ieerfnezln5fifjy3oxetq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.13-SNAPSHOT.jar",
          "url": "javapackager-1.6.13-SNAPSHOT.jar",
          "size": 413068,
          "sha512": "5b47e0be0e791144f7153c01dcffd3eba702931aca00ca7f9ddea82343ab99cb6a0500f6feda5078fc3878a6de13b87efe8b080ccc0bd6d749a384d30fb311df",
          "sha256": "fca25945d8bc0fc7bcab8de34c04097805a7ae3fe02169f12fb7ee75b571f306",
          "sha1": "b4b0bb25a83f01d8631e080f9dad1dc3e5ae9e00",
          "md5": "a0884f7cddaa3240a490883d8b4363a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "edu.sc.seis.launch4j",
          "module": "launch4j",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-ospackage-plugin",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.13-SNAPSHOT.jar",
          "url": "javapackager-1.6.13-SNAPSHOT.jar",
          "size": 413068,
          "sha512": "5b47e0be0e791144f7153c01dcffd3eba702931aca00ca7f9ddea82343ab99cb6a0500f6feda5078fc3878a6de13b87efe8b080ccc0bd6d749a384d30fb311df",
          "sha256": "fca25945d8bc0fc7bcab8de34c04097805a7ae3fe02169f12fb7ee75b571f306",
          "sha1": "b4b0bb25a83f01d8631e080f9dad1dc3e5ae9e00",
          "md5": "a0884f7cddaa3240a490883d8b4363a4"
        }
      ]
    }
  ]
}
