{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2jb534vyzbg5jlxlgceny7ek3a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.5-SNAPSHOT.jar",
          "url": "javapackager-1.6.5-SNAPSHOT.jar",
          "size": 411714,
          "sha512": "38ad440a52897255702d40abee68bed995fd08a801e342457e29896d0a320b9911528cf128755c879eba7a8b3f2e6c0ecfde24352b7a2a8b79dc46ced048148f",
          "sha256": "bb4746c4c8db02802553029f8f673b1a8c40bb387a9bb958348eb523da00dc7d",
          "sha1": "3e686dc802f06e2487b140868fd52bc6d399d12f",
          "md5": "c8430441fd9f29796b66c376131f8bd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "edu.sc.seis.gradle",
          "module": "launch4j",
          "version": {
            "requires": "2.4.8-LOCAL"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-ospackage-plugin",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.5-SNAPSHOT.jar",
          "url": "javapackager-1.6.5-SNAPSHOT.jar",
          "size": 411714,
          "sha512": "38ad440a52897255702d40abee68bed995fd08a801e342457e29896d0a320b9911528cf128755c879eba7a8b3f2e6c0ecfde24352b7a2a8b79dc46ced048148f",
          "sha256": "bb4746c4c8db02802553029f8f673b1a8c40bb387a9bb958348eb523da00dc7d",
          "sha1": "3e686dc802f06e2487b140868fd52bc6d399d12f",
          "md5": "c8430441fd9f29796b66c376131f8bd9"
        }
      ]
    }
  ]
}
