{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.6-WHY3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "gf3wp5y5srhzxfq6mlsyseagou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.6-WHY3.jar",
          "url": "javapackager-1.6.6-WHY3.jar",
          "size": 1454103,
          "sha512": "82eff41b98b56e87d1f92444ba66fbc20208c6e9aec91c48826244c299b4f82fc29114114365a764d02b0743f0306db4a1aeb7386a77f1173eb10c7784d4cd3f",
          "sha256": "672b5e489c935ca572e5c03fdd5ed4510bc4ae5374dd8a41947f5529beb1035c",
          "sha1": "f7b8c353f1393670448d9448ed71453bcdb9ac17",
          "md5": "ac45c60efd720bde697b8c0c8733f9c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "launch4j",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.6-WHY3.jar",
          "url": "javapackager-1.6.6-WHY3.jar",
          "size": 1454103,
          "sha512": "82eff41b98b56e87d1f92444ba66fbc20208c6e9aec91c48826244c299b4f82fc29114114365a764d02b0743f0306db4a1aeb7386a77f1173eb10c7784d4cd3f",
          "sha256": "672b5e489c935ca572e5c03fdd5ed4510bc4ae5374dd8a41947f5529beb1035c",
          "sha1": "f7b8c353f1393670448d9448ed71453bcdb9ac17",
          "md5": "ac45c60efd720bde697b8c0c8733f9c2"
        }
      ]
    }
  ]
}
