{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.6-WHY3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3dzfb7t3mbbjphdmkuofn573ei"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.6-WHY3.jar",
          "url": "javapackager-1.6.6-WHY3.jar",
          "size": 1454794,
          "sha512": "c167155db9f0f57fd99ec5d7b0aaf1cb67bf1bcd574e10ce7f687b2e8bd1069be1e25331fc16376b0268c9ab4cfe864a3afe05a4542600474c33ff881e5198bc",
          "sha256": "f44848a7534156a735a3099581f2bee3315e84c7aeea1d668edf39e63f3b23d1",
          "sha1": "eeea4f408266a234213c8f168db01cb345239c1b",
          "md5": "920e212d23fb5b944040ee3ddddc1d3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "launch4j",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.6-WHY3.jar",
          "url": "javapackager-1.6.6-WHY3.jar",
          "size": 1454794,
          "sha512": "c167155db9f0f57fd99ec5d7b0aaf1cb67bf1bcd574e10ce7f687b2e8bd1069be1e25331fc16376b0268c9ab4cfe864a3afe05a4542600474c33ff881e5198bc",
          "sha256": "f44848a7534156a735a3099581f2bee3315e84c7aeea1d668edf39e63f3b23d1",
          "sha1": "eeea4f408266a234213c8f168db01cb345239c1b",
          "md5": "920e212d23fb5b944040ee3ddddc1d3d"
        }
      ]
    }
  ]
}
