/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AIJ.Merged;

import ij.ImageJ;

public class AijMerged {
    public static void main(String[] args) {
        ImageJ.main(args);
    }
}
