{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uggmc53npbe3lcpzf6d64svk3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.7-SNAPSHOT.jar",
          "url": "javapackager-1.6.7-SNAPSHOT.jar",
          "size": 1420585,
          "sha512": "4a1139799c6285cc74c5665f20f7e2588ffeb527c5235654ac3ce17bae201eceac4a06371c8d67337404ea5a007e60a254bcb9bafcadc916d18bf402c2950fe5",
          "sha256": "bed4841f1d49f67611224b15ca81d5ac60fe8a2326628cf2ccae4f8f925b2500",
          "sha1": "61637c2b17092e948ac59f7142f442632d2da99e",
          "md5": "81f1c45717e91a5aff58138c217270a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "launch4j",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.7-SNAPSHOT.jar",
          "url": "javapackager-1.6.7-SNAPSHOT.jar",
          "size": 1420585,
          "sha512": "4a1139799c6285cc74c5665f20f7e2588ffeb527c5235654ac3ce17bae201eceac4a06371c8d67337404ea5a007e60a254bcb9bafcadc916d18bf402c2950fe5",
          "sha256": "bed4841f1d49f67611224b15ca81d5ac60fe8a2326628cf2ccae4f8f925b2500",
          "sha1": "61637c2b17092e948ac59f7142f442632d2da99e",
          "md5": "81f1c45717e91a5aff58138c217270a4"
        }
      ]
    }
  ]
}
