{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4jcctph37vhkxc6p3x46okwisy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.7-SNAPSHOT.jar",
          "url": "javapackager-1.6.7-SNAPSHOT.jar",
          "size": 1420369,
          "sha512": "e120b0fc6247db0cf6c2b696134d997a549a65b16649e5d32cfe052f34e3617c2835d9a059da42b565c7884e265bff7cabd4a24342e482150bd7a204107063db",
          "sha256": "d45e9bbad1d8cee44fdaef83371682079532d844d8f63fc445d4396b1645684e",
          "sha1": "8b3be457cd5768812639a18664483467f34b84ce",
          "md5": "b1345aec98280f75bc592839482ff928"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "launch4j",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.7-SNAPSHOT.jar",
          "url": "javapackager-1.6.7-SNAPSHOT.jar",
          "size": 1420369,
          "sha512": "e120b0fc6247db0cf6c2b696134d997a549a65b16649e5d32cfe052f34e3617c2835d9a059da42b565c7884e265bff7cabd4a24342e482150bd7a204107063db",
          "sha256": "d45e9bbad1d8cee44fdaef83371682079532d844d8f63fc445d4396b1645684e",
          "sha1": "8b3be457cd5768812639a18664483467f34b84ce",
          "md5": "b1345aec98280f75bc592839482ff928"
        }
      ]
    }
  ]
}
