{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dfy25nwfmfdfddkxpzh3zyt3je"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.11-SNAPSHOT.jar",
          "url": "javapackager-1.6.11-SNAPSHOT.jar",
          "size": 413153,
          "sha512": "858185b11b4e49a9d6e24ec4d3e5fd199a6f7247a55b2bb8c969511992ecaefd4d3bc7e415de2bed48f1f436f3f63247696b9c05b462fb199d6aab0138f199ab",
          "sha256": "27741abfb7f6920312b91950bc258c48068cc6f72ac01f89a949e5dc6fe52edf",
          "sha1": "2f7d17f4f3cba0595f72ceee1e95ffab461c471c",
          "md5": "dd784baafc141bdfb6ab2e6e4b3fa5fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "edu.sc.seis.launch4j",
          "module": "launch4j",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-ospackage-plugin",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.11-SNAPSHOT.jar",
          "url": "javapackager-1.6.11-SNAPSHOT.jar",
          "size": 413153,
          "sha512": "858185b11b4e49a9d6e24ec4d3e5fd199a6f7247a55b2bb8c969511992ecaefd4d3bc7e415de2bed48f1f436f3f63247696b9c05b462fb199d6aab0138f199ab",
          "sha256": "27741abfb7f6920312b91950bc258c48068cc6f72ac01f89a949e5dc6fe52edf",
          "sha1": "2f7d17f4f3cba0595f72ceee1e95ffab461c471c",
          "md5": "dd784baafc141bdfb6ab2e6e4b3fa5fe"
        }
      ]
    }
  ]
}
