{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "65yll7gqxjgefixqe5idfexudi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.7.1-SNAPSHOT.jar",
          "url": "javapackager-1.7.1-SNAPSHOT.jar",
          "size": 1324327,
          "sha512": "fb738d28abb532ae65186a9b4876a05f9db405cbafd21c0b72ebd3ba6731cbf3f4cb6e2fa7002065a99620cbdd304c1385a20c2796d53d3376187abff5123a37",
          "sha256": "a38ec341a0b58ed34bf872dd063345bbc04449c3f195a6139fbe2f4a90eff47f",
          "sha1": "74d86d9d7f3da1254fd2c353eb352fd77e3e2b14",
          "md5": "42436ed1e96d5da7fe7913e637336c28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "edu.sc.seis.launch4j",
          "module": "launch4j",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.7.1-SNAPSHOT.jar",
          "url": "javapackager-1.7.1-SNAPSHOT.jar",
          "size": 1324327,
          "sha512": "fb738d28abb532ae65186a9b4876a05f9db405cbafd21c0b72ebd3ba6731cbf3f4cb6e2fa7002065a99620cbdd304c1385a20c2796d53d3376187abff5123a37",
          "sha256": "a38ec341a0b58ed34bf872dd063345bbc04449c3f195a6139fbe2f4a90eff47f",
          "sha1": "74d86d9d7f3da1254fd2c353eb352fd77e3e2b14",
          "md5": "42436ed1e96d5da7fe7913e637336c28"
        }
      ]
    }
  ]
}
