{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3tnfk37ab5g4pa5j72jq3g3f7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.1-SNAPSHOT.jar",
          "url": "javapackager-1.6.1-SNAPSHOT.jar",
          "size": 411686,
          "sha512": "9ce8378304357468b1deaca2d45bcd2914aadfc5e895c6540daebcda819369738413bb662419a5ba2d81e5f9d865a47462be62413e04a6c0aec3b424cc502b07",
          "sha256": "d479eb5bbe946b5c4f4f92cc19d381f10136655109a68b373161c7d975a13533",
          "sha1": "ffd53f10c28aa15c2157a03dfbbddd8fde556f5f",
          "md5": "7ea090f28fe9178e1ca0e106f720d3f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "edu.sc.seis.launch4j",
          "module": "launch4j",
          "version": {
            "requires": "2.5.1-LOCAL"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-ospackage-plugin",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.1-SNAPSHOT.jar",
          "url": "javapackager-1.6.1-SNAPSHOT.jar",
          "size": 411686,
          "sha512": "9ce8378304357468b1deaca2d45bcd2914aadfc5e895c6540daebcda819369738413bb662419a5ba2d81e5f9d865a47462be62413e04a6c0aec3b424cc502b07",
          "sha256": "d479eb5bbe946b5c4f4f92cc19d381f10136655109a68b373161c7d975a13533",
          "sha1": "ffd53f10c28aa15c2157a03dfbbddd8fde556f5f",
          "md5": "7ea090f28fe9178e1ca0e106f720d3f1"
        }
      ]
    }
  ]
}
