{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kulvizb3bffzldryw4t6xkroca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.12-SNAPSHOT.jar",
          "url": "javapackager-1.6.12-SNAPSHOT.jar",
          "size": 413951,
          "sha512": "4b1a5ee7d3ef837766ea54e937788c6eaed633e3b4864a8b7d4f9b5b615b88d092eed77052e80972d1a03127b3a41ab028918a54c98ee8453825566ccb0a7c2b",
          "sha256": "4aa1c3ba29f15458af150630d26da14fd8f3c008bf4446c93655fbd5f02c1283",
          "sha1": "1671054d6182cc1af12a85b88f35a386fbd06fd2",
          "md5": "eda5c017aad7a05463544180c6e8a970"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "edu.sc.seis.launch4j",
          "module": "launch4j",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-ospackage-plugin",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.12-SNAPSHOT.jar",
          "url": "javapackager-1.6.12-SNAPSHOT.jar",
          "size": 413951,
          "sha512": "4b1a5ee7d3ef837766ea54e937788c6eaed633e3b4864a8b7d4f9b5b615b88d092eed77052e80972d1a03127b3a41ab028918a54c98ee8453825566ccb0a7c2b",
          "sha256": "4aa1c3ba29f15458af150630d26da14fd8f3c008bf4446c93655fbd5f02c1283",
          "sha1": "1671054d6182cc1af12a85b88f35a386fbd06fd2",
          "md5": "eda5c017aad7a05463544180c6e8a970"
        }
      ]
    }
  ]
}
