{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.6-WHY",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wdqmrsjig5bb3a6j5nzn442emm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.6-WHY.jar",
          "url": "javapackager-1.6.6-WHY.jar",
          "size": 1452022,
          "sha512": "21a842f5ef4ead7bdc4ba900e4cb5c4e7abfc575bdcce0ddebcc5523924286f4c47429633999e60f8a68ed1dcfea25ade66d3e0a7814ebedcc08959240c1a4dd",
          "sha256": "acec35176b3512ef92841875cc3d14a6a810d2b2ef2ddd7a65215b62de7073ba",
          "sha1": "06eb8927237763ae3a56dfc3dd8b9343c2afc106",
          "md5": "6ad67a1491424ef04ce574e14acf1615"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "launch4j",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.6-WHY.jar",
          "url": "javapackager-1.6.6-WHY.jar",
          "size": 1452022,
          "sha512": "21a842f5ef4ead7bdc4ba900e4cb5c4e7abfc575bdcce0ddebcc5523924286f4c47429633999e60f8a68ed1dcfea25ade66d3e0a7814ebedcc08959240c1a4dd",
          "sha256": "acec35176b3512ef92841875cc3d14a6a810d2b2ef2ddd7a65215b62de7073ba",
          "sha1": "06eb8927237763ae3a56dfc3dd8b9343c2afc106",
          "md5": "6ad67a1491424ef04ce574e14acf1615"
        }
      ]
    }
  ]
}
