{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.32-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "z5vob7wmn5bspltuz2umi3nzoy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.32-SNAPSHOT.jar",
          "url": "javapackager-1.6.32-SNAPSHOT.jar",
          "size": 420613,
          "sha512": "1a4cdd7985f367ca0d809e0698352d41cdb088b220cf8ef3a4f6b1b005d81c5b9add1d694a904de0c50ae415ca49b84be589999f6ca486b303727738ede49c36",
          "sha256": "a322167df09ccfdf4105dd83ba2e69728db7b9a1fbd81209b6242ce50d2712dd",
          "sha1": "da279a7a9bd81564ba996cf12dbd664e4d766c02",
          "md5": "ff7ccf52a182eb074bdba5b07745d586"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "gradle-launch4j",
          "version": {
            "requires": "2.4.7"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.32-SNAPSHOT.jar",
          "url": "javapackager-1.6.32-SNAPSHOT.jar",
          "size": 420613,
          "sha512": "1a4cdd7985f367ca0d809e0698352d41cdb088b220cf8ef3a4f6b1b005d81c5b9add1d694a904de0c50ae415ca49b84be589999f6ca486b303727738ede49c36",
          "sha256": "a322167df09ccfdf4105dd83ba2e69728db7b9a1fbd81209b6242ce50d2712dd",
          "sha1": "da279a7a9bd81564ba996cf12dbd664e4d766c02",
          "md5": "ff7ccf52a182eb074bdba5b07745d586"
        }
      ]
    }
  ]
}
