{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2oitegynhza4dcjp6voth77bqy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.16-SNAPSHOT.jar",
          "url": "javapackager-1.6.16-SNAPSHOT.jar",
          "size": 412769,
          "sha512": "f6c1921bb78fc5cef16f105a5368886e07fa56ec0bbc444dd43b86d90e7bc58bdab18389e7d3dc87cb27b6db4bf51071695bdf6ddfd51f7184d62309ba0f801a",
          "sha256": "7849c16b9ea785a7e98ed15eb9c38f7ace6895f93b4668c8d8df58a07d6912a7",
          "sha1": "1b19c17bf0502915423a7d51504e7df8da08ad1d",
          "md5": "5cee3b05f63fea845ec0966bba324d35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "edu.sc.seis.launch4j",
          "module": "launch4j",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-ospackage-plugin",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.16-SNAPSHOT.jar",
          "url": "javapackager-1.6.16-SNAPSHOT.jar",
          "size": 412769,
          "sha512": "f6c1921bb78fc5cef16f105a5368886e07fa56ec0bbc444dd43b86d90e7bc58bdab18389e7d3dc87cb27b6db4bf51071695bdf6ddfd51f7184d62309ba0f801a",
          "sha256": "7849c16b9ea785a7e98ed15eb9c38f7ace6895f93b4668c8d8df58a07d6912a7",
          "sha1": "1b19c17bf0502915423a7d51504e7df8da08ad1d",
          "md5": "5cee3b05f63fea845ec0966bba324d35"
        }
      ]
    }
  ]
}
