{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fc5v6a5ccjd2phwe2ulk2pjunq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.18-SNAPSHOT.jar",
          "url": "javapackager-1.6.18-SNAPSHOT.jar",
          "size": 415204,
          "sha512": "f3c87ba73112b5647c411c33116069823d79eaad6d1b161980cfbb0e83e692db0f21bda82eb18427e2e18b394fa4669bd2e15d71b3665dfe5efc87cb1b8d79df",
          "sha256": "7cdcd2f8d2983bbe9059f404ed11cd3e761eed70ce2dabe0ef01b6c0ba8fe94e",
          "sha1": "c244dc9e88d9502554d9fe39b18eff9f74540c2a",
          "md5": "1c1a2d2977ed07e8d24a4124daf09c50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "gradle-launch4j",
          "version": {
            "requires": "2.4.7"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-ospackage-plugin",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.18-SNAPSHOT.jar",
          "url": "javapackager-1.6.18-SNAPSHOT.jar",
          "size": 415204,
          "sha512": "f3c87ba73112b5647c411c33116069823d79eaad6d1b161980cfbb0e83e692db0f21bda82eb18427e2e18b394fa4669bd2e15d71b3665dfe5efc87cb1b8d79df",
          "sha256": "7cdcd2f8d2983bbe9059f404ed11cd3e761eed70ce2dabe0ef01b6c0ba8fe94e",
          "sha1": "c244dc9e88d9502554d9fe39b18eff9f74540c2a",
          "md5": "1c1a2d2977ed07e8d24a4124daf09c50"
        }
      ]
    }
  ]
}
