{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "jydkn3okcvcdlbzjavhh4y6dre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.4.0-SNAPSHOT.jar",
          "url": "javapackager-1.4.0-SNAPSHOT.jar",
          "size": 379449,
          "sha512": "8eb1704447e86f2e4ccc2adbb28cf32f2a30d8b03e47266fcc38001c2a0d6645c72100a4605659672f7466e31d989ad9597d1c84309ea024b5dccd782afc0d19",
          "sha256": "ce72954d04f9d5f3eaaa4df6e3e045863d15771583ff5a00539947b2e5ee3767",
          "sha1": "b26fed65fca4a54a6245818a4496bed5c8f25e49",
          "md5": "dd58274bf2118a7e1965008e261c223d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "gradle-launch4j",
          "version": {
            "requires": "2.4.7"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.4.0-SNAPSHOT.jar",
          "url": "javapackager-1.4.0-SNAPSHOT.jar",
          "size": 379449,
          "sha512": "8eb1704447e86f2e4ccc2adbb28cf32f2a30d8b03e47266fcc38001c2a0d6645c72100a4605659672f7466e31d989ad9597d1c84309ea024b5dccd782afc0d19",
          "sha256": "ce72954d04f9d5f3eaaa4df6e3e045863d15771583ff5a00539947b2e5ee3767",
          "sha1": "b26fed65fca4a54a6245818a4496bed5c8f25e49",
          "md5": "dd58274bf2118a7e1965008e261c223d"
        }
      ]
    }
  ]
}
