{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "y7dozqhfojbgtkrtqapxqntndu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.4.0-SNAPSHOT.jar",
          "url": "javapackager-1.4.0-SNAPSHOT.jar",
          "size": 378907,
          "sha512": "cb8a1470c83da791381feae6e1f3200045f72defd78ce9a01aba9b1480a199091d625ac2505dfb6eab66ee6e4899e1ca639e474c7d4c67545a0d9406d289752c",
          "sha256": "d22eb61a00aafadb7be96b7059af78aaff8ad70731cdd7978e37642844b9e0d7",
          "sha1": "058582f365e0ecb966938960b416d391c38440df",
          "md5": "35cf88843d5bfca40192e21864cb43e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "gradle-launch4j",
          "version": {
            "requires": "2.4.7"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.4.0-SNAPSHOT.jar",
          "url": "javapackager-1.4.0-SNAPSHOT.jar",
          "size": 378907,
          "sha512": "cb8a1470c83da791381feae6e1f3200045f72defd78ce9a01aba9b1480a199091d625ac2505dfb6eab66ee6e4899e1ca639e474c7d4c67545a0d9406d289752c",
          "sha256": "d22eb61a00aafadb7be96b7059af78aaff8ad70731cdd7978e37642844b9e0d7",
          "sha1": "058582f365e0ecb966938960b416d391c38440df",
          "md5": "35cf88843d5bfca40192e21864cb43e4"
        }
      ]
    }
  ]
}
