{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "osrxuh7bendrxh5ullj2nkzx2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.4.0-SNAPSHOT.jar",
          "url": "javapackager-1.4.0-SNAPSHOT.jar",
          "size": 378877,
          "sha512": "d01a611ee217af6a1e4b354973ab80919a5ad5d1717b2ecd68b53fed8e63b180f0a47a33de956933dbb63b1590d004ad41475fd507156dce520df7716dc5d5cd",
          "sha256": "7740680e0aadef22e3be6b4c91721393b25e60de28ebb04e09ed47cfae056407",
          "sha1": "c5a5895833a1e09c3fb8bfbece9fe6897a2165ac",
          "md5": "d460cf331463c3c8895e2ce8a157e905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "gradle-launch4j",
          "version": {
            "requires": "2.4.7"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.4.0-SNAPSHOT.jar",
          "url": "javapackager-1.4.0-SNAPSHOT.jar",
          "size": 378877,
          "sha512": "d01a611ee217af6a1e4b354973ab80919a5ad5d1717b2ecd68b53fed8e63b180f0a47a33de956933dbb63b1590d004ad41475fd507156dce520df7716dc5d5cd",
          "sha256": "7740680e0aadef22e3be6b4c91721393b25e60de28ebb04e09ed47cfae056407",
          "sha1": "c5a5895833a1e09c3fb8bfbece9fe6897a2165ac",
          "md5": "d460cf331463c3c8895e2ce8a157e905"
        }
      ]
    }
  ]
}
