{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hhizbdtjava6vjqtemwjogpmoe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.0-SNAPSHOT.jar",
          "url": "javapackager-1.6.0-SNAPSHOT.jar",
          "size": 411660,
          "sha512": "584b832f128607bec9b99c178662cf13a659f60b82967af37733363fe154253f73433483866f8676281e21ba5150515906bbf326b6aa1cef6df6f70cd8d8fe54",
          "sha256": "b227c9cb5bcd30e8b3b97fd63a4008a3f332d5c8c1a0beb6ecd7880a0222fe0a",
          "sha1": "91eefec0465f44b34b381f458352b2294144e2cf",
          "md5": "d9c9e76153ec9ebcf14a3242b6973db3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "edu.sc.seis.launch4j",
          "module": "launch4j",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-ospackage-plugin",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.0-SNAPSHOT.jar",
          "url": "javapackager-1.6.0-SNAPSHOT.jar",
          "size": 411660,
          "sha512": "584b832f128607bec9b99c178662cf13a659f60b82967af37733363fe154253f73433483866f8676281e21ba5150515906bbf326b6aa1cef6df6f70cd8d8fe54",
          "sha256": "b227c9cb5bcd30e8b3b97fd63a4008a3f332d5c8c1a0beb6ecd7880a0222fe0a",
          "sha1": "91eefec0465f44b34b381f458352b2294144e2cf",
          "md5": "d9c9e76153ec9ebcf14a3242b6973db3"
        }
      ]
    }
  ]
}
