{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.6.23-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fl3o3om46jcqrjv3kn2g2fsx3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.6.23-SNAPSHOT.jar",
          "url": "javapackager-1.6.23-SNAPSHOT.jar",
          "size": 420613,
          "sha512": "b3c6be53bbd69d53f442a2ee908fd35bc0c62a8a12fddd19842654b0bc615ddb7e9b59857e72f93da7f3031f70aefd450f0bd09a17c9fd329626133846ac8298",
          "sha256": "7d6e0a6dadfd51240e1fa20dd61be6e9c05cbb10397e175c43ab6e5137b12541",
          "sha1": "9649d1d78ed57375cff385deb37e667bfe5d0f2f",
          "md5": "69addbd08d97f26c87b9f89e7351ebd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.github.fvarrui",
          "module": "gradle-launch4j",
          "version": {
            "requires": "2.4.7"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.6.23-SNAPSHOT.jar",
          "url": "javapackager-1.6.23-SNAPSHOT.jar",
          "size": 420613,
          "sha512": "b3c6be53bbd69d53f442a2ee908fd35bc0c62a8a12fddd19842654b0bc615ddb7e9b59857e72f93da7f3031f70aefd450f0bd09a17c9fd329626133846ac8298",
          "sha256": "7d6e0a6dadfd51240e1fa20dd61be6e9c05cbb10397e175c43ab6e5137b12541",
          "sha1": "9649d1d78ed57375cff385deb37e667bfe5d0f2f",
          "md5": "69addbd08d97f26c87b9f89e7351ebd6"
        }
      ]
    }
  ]
}
