/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AIJ.Merged;

import org.junit.Test;
import static org.junit.Assert.*;

public class AijMergedTest {
    @Test public void testAppHasAGreeting() {
        AijMerged classUnderTest = new AijMerged();
    }
}
