{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fvarrui",
    "module": "javapackager",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "a4hx2vw2fbgcvdycmvrfvct7de"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javapackager-1.7.0-SNAPSHOT.jar",
          "url": "javapackager-1.7.0-SNAPSHOT.jar",
          "size": 1290672,
          "sha512": "c18709e70d26dcc0afac6eca42212bd9abaf48e0e7445ca11afe729f96f40058876ba2539b9723bc509cde4206f7ca1a4146a2bbf21e0a97d7c23a5d9af2831a",
          "sha256": "e7870a107bda2a8a432939b428c94e5f419ea77bcb83cecd938f352768af9245",
          "sha1": "7360d948ab4381d401a50296fc61a552eed6e702",
          "md5": "09d885e4e799ba2c8825c0b971fbad63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-utils",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.vafer",
          "module": "jdeb",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "net.jsign",
          "module": "jsign-core",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "org.redline-rpm",
          "module": "redline",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "edu.sc.seis.launch4j",
          "module": "launch4j",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "javapackager-1.7.0-SNAPSHOT.jar",
          "url": "javapackager-1.7.0-SNAPSHOT.jar",
          "size": 1290672,
          "sha512": "c18709e70d26dcc0afac6eca42212bd9abaf48e0e7445ca11afe729f96f40058876ba2539b9723bc509cde4206f7ca1a4146a2bbf21e0a97d7c23a5d9af2831a",
          "sha256": "e7870a107bda2a8a432939b428c94e5f419ea77bcb83cecd938f352768af9245",
          "sha1": "7360d948ab4381d401a50296fc61a552eed6e702",
          "md5": "09d885e4e799ba2c8825c0b971fbad63"
        }
      ]
    }
  ]
}
